inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.5
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1

require:
  - rubocop-performance
  - rubocop-rspec

RSpec/FilePath:
  Exclude:
    - spec/integration_spec.rb
