inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.7
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-performance
  - rubocop-rspec

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/HashAlignment:
  EnforcedColonStyle: table

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration_spec.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false
