# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

default: &default
  docker:
    - image: ruby:slim
  environment:
    # c.f. https://github.com/ffaker/ffaker/issues/277#issuecomment-263519146
    LANG:     en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LC_ALL:   C.UTF-8

  working_directory: ~/app

restore_repo_cache_option: &restore_repo_cache_option
  key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v1-bundle-{{ checksum "itest5ch.gemspec" }}
    - v1-bundle

jobs:
  checkout_code:
    <<: *default

    steps:
      - checkout

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup.sh
      - save_cache:
          key: v1-bundle-{{ checksum "itest5ch.gemspec" }}
          paths:
            - ~/app/vendor/bundle

  rspec:
    <<: *default

    docker:
      - image: ruby:2.5-slim

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup.sh
      - run: bundle exec rspec

  rubocop:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup.sh
      - run: bundle exec rubocop

workflows:
  version: 2

  build:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs:
      - build
