# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: ruby:<< parameters.tag >>
    environment:
      # c.f. https://github.com/ffaker/ffaker/issues/277#issuecomment-263519146
      LANG:     en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL:   C.UTF-8

      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      CC_TEST_REPORTER_ID: d91e7c9665019f1574eb4c5a3de1547c80bc3062e3c297282f106501a3c5c694
    working_directory: ~/app

commands:
  with-cc-test-reporter:
    description: "Run test with cc-test-reporter"
    parameters:
      steps:
        type: steps
        default: []
        description: "Run steps between `before-build` and `after-build`"
    steps:
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - steps: << parameters.steps >>
      - run:
          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
          when: always

jobs:
  rspec:
    parameters:
      version:
        type: string
    executor:
      name: ruby
      tag: << parameters.version >>
    steps:
      - checkout
      - run: ruby --version
      - run: bundle --version
      - run: gem --version
      - ruby-orbs/bundle-install:
          with_gemfile_lock: false
          gemspec_name: "itest5ch"
          update_always: true
      - with-cc-test-reporter:
          steps:
            - run: bundle exec rspec

  rubocop:
    executor:
      name: ruby

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          with_gemfile_lock: false
          gemspec_name: "itest5ch"
          update_always: true

      - run: bundle exec rubocop

build_jobs: &build_jobs
  - rspec:
      name:    "rspec:2.3"
      version: "2.3"
  - rspec:
      name:    "rspec:2.4"
      version: "2.4"
  - rspec:
      name:    "rspec:2.5"
      version: "2.5"
  - rspec:
      name:    "rspec:2.6"
      version: "2.6"
  - rubocop

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
