# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

default: &default
  environment:
    # c.f. https://github.com/ffaker/ffaker/issues/277#issuecomment-263519146
    LANG:     en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LC_ALL:   C.UTF-8

    BUNDLE_PATH: vendor/bundle
    BUNDLE_JOBS: 4
    CODECLIMATE_REPO_TOKEN: d91e7c9665019f1574eb4c5a3de1547c80bc3062e3c297282f106501a3c5c694

  working_directory: ~/app

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: ruby:<< parameters.tag >>

commands:
  setup_bundle:
    description: "Setup bundle with cache"
    steps:
      - restore_cache:
          keys:
            - v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "itest5ch.gemspec" }}
            - v3-bundle-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Setup
          command: |
            set -xe
            ruby --version
            bundle --version
            gem --version

            bundle update
            bundle clean

      - save_cache:
          key: v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "itest5ch.gemspec" }}
          paths:
            - ~/app/vendor/bundle
            - ~/app/Gemfile.lock

jobs:
  rspec:
    <<: *default

    parameters:
      version:
        type: string
    executor:
      name: ruby
      tag: << parameters.version >>
    steps:
      - checkout
      - setup_bundle

      - run: bundle exec rspec
      - run: bundle exec codeclimate-test-reporter

  rubocop:
    <<: *default

    executor:
      name: ruby

    steps:
      - checkout
      - setup_bundle

      - run: bundle exec rubocop

build_jobs: &build_jobs
  - rspec:
      name:    "rspec:2.3"
      version: "2.3"
  - rspec:
      name:    "rspec:2.4"
      version: "2.4"
  - rspec:
      name:    "rspec:2.5"
      version: "2.5"
  - rubocop

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
