# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

default: &default
  docker:
    - image: ruby
  environment:
    # c.f. https://github.com/ffaker/ffaker/issues/277#issuecomment-263519146
    LANG:     en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LC_ALL:   C.UTF-8

    BUNDLE_PATH: vendor/bundle
    BUNDLE_JOBS: 4
    CODECLIMATE_REPO_TOKEN: d91e7c9665019f1574eb4c5a3de1547c80bc3062e3c297282f106501a3c5c694

  working_directory: ~/app

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "itest5ch.gemspec" }}
    - v3-bundle-{{ .Environment.CIRCLE_JOB }}

save_bundle_cache_option: &save_bundle_cache_option
  key: v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "itest5ch.gemspec" }}
  paths:
    - ~/app/vendor/bundle
    - ~/app/Gemfile.lock

rspec_steps: &rspec_steps
  - checkout
  - restore_cache:
      <<: *restore_bundle_cache_option
  - run: ./.circleci/setup.sh
  - save_cache:
      <<: *save_bundle_cache_option

  - run: bundle exec rspec
  - run: bundle exec codeclimate-test-reporter

build_jobs: &build_jobs
  - rspec:2.3
  - rspec:2.4
  - rspec:2.5
  - rubocop

jobs:
  rspec:2.3:
    <<: *default

    docker:
      - image: ruby:2.3

    steps: *rspec_steps

  rspec:2.4:
    <<: *default

    docker:
      - image: ruby:2.4

    steps: *rspec_steps

  rspec:2.5:
    <<: *default

    docker:
      - image: ruby:2.5

    steps: *rspec_steps

  rubocop:
    <<: *default

    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup.sh
      - save_cache:
          <<: *save_bundle_cache_option

      - run: bundle exec rubocop

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
